language: julia
os:
  - linux
julia:
  - 1.0
notifications:
  email: false
git:
  depth: 99999999
cache:
  directories:
    - downloads
env:
  global:
    - BINARYBUILDER_DOWNLOADS_CACHE=downloads
    - BINARYBUILDER_AUTOMATIC_APPLE=true
sudo: required

# Before anything else, get the latest versions of things
before_script:
  - julia -e 'using Pkg; Pkg.add([PackageSpec(name="BinaryBuilder", rev="master"), PackageSpec(name="MbedTLS", version=v"0.6.6"), PackageSpec(name="BinaryProvider")])'

script:
  - julia --color=yes build_tarballs.jl

deploy:
  provider: releases
  api_key:
    secure: k81kCkuzI1K9rYuuPORWD2JUtsJfLzipqaAzzh8aqIe5IOJzBqD7XgHDLbAzDqHJ9FB7Ij+sUFblN1ajwdJ+BVvYEn1prfMaTrMdncYSzhNNRVQ7m7I0h9vPJB26LwtMzW+MfR+X2ghsTBbdhdrPrluO+XAef60w8V787KiNvdG+xjMGpfNJi5lNR5TKyCZz1wpOtKBvG2+nAcd/AsAwnZGmD+6P8GtS4nfp2y4dAH1y+EmRbauz0dTXTiY0lqjNQ+sLNeQvKNwXlRfOlMJJTvTz1D9HxuuniQryAgFlnKok1g/YoLOln8kbhQjyREl3FtC32XNf4QhrHT1o45NRMoKDgHz0dId+HrydNUAfjK2C716QdNlj1vAjmtNKCDylLMxsYjPxooOtKma8YBFEtdmJJZ/q4YEC/c0oCL9TTMYC001m3p4vP74AidRvYq9UUCblV78xa8ECstJMEvJVwd/SdXmB2f3s6QYzhU2iRsBGolvcHpEnAozvVCYFlkJAL2gql1i/m7W6qMZV7fUNtdQt+C72MyQ3uadAYTgEBvAIUDcuyh3Cce63sQVetHzFRS5OmWpg72/ehkCJF4+JEWYgB+OFD5LI+1hbkWkxjSVJX+taJmbhk9ZAj3pZEcyZ9QLmaYLUvNju+wWbfwaUNKbAQu9ShoPUNenfrBzF+XU=
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: findmyway/VisualDLBuilder
    tags: true
